In [1]:
import pandas as pd
import numpy as np
import re

In [2]:
df = pd.read_csv("sharks_df.csv")

Cleaning the Age Column

In [3]:
#clean age column
df["Age"] = df["Age"].replace("?", "Unknown").fillna("Unknown").replace("s", "")
print(df)

             Date    Year          Type             Country  \
0        24th May  2026.0    Unprovoked           Australia
1        17th May  2026.0  Questionable                 USA
2        16th May  2026.0    Unprovoked           Australia
3      14th April  2026.0    UNprovoked            Maldives
4       3rd April  2026.0    Unprovoked           Australia
...           ...     ...           ...                 ...
7085  Before 1903     0.0    Unprovoked           AUSTRALIA
7086  Before 1903     0.0    Unprovoked           AUSTRALIA
7087    1900-1905     0.0    Unprovoked                 USA
7088    1883-1889     0.0    Unprovoked              PANAMA
7089    1845-1853     0.0    Unprovoked  CEYLON (SRI LANKA)

                  State                                     Location  \
0            Queensland                                Kennedy Shoal
1              Maryland                        Assateague State Park
2     Western Australia              Horseshoe Reef  Rottnest Island
3      Gaafu Alif Atoll                                      Kooddoo
4       South Australia  Middleton Beach Fleurieu Peninsula Adelaide
...                 ...                                          ...
7085  Western Australia                                  Roebuck Bay
7086  Western Australia                                          NaN
7087     North Carolina                               Ocracoke Inlet
7088                NaN                         Panama Bay 8ºN, 79ºW
7089   Eastern Province          Below the English fort, Trincomalee

          Activity                       Name Sex      Age  ...  \
0     Spearfishing              Michael Jensz   M       39  ...
1          Surfing              Brendan Oster   M  Unknown  ...
2       Skindiving           Steven Mattaboni   M       38  ...
3         Swimming  Not stated - on honeymoon   M  Unknown  ...
4          Surfing       Oliver Tokic-Bensley   M       16  ...
...            ...                        ...  ..      ...  ...
7085        Diving                       male   M  Unknown  ...
7086  Pearl diving                      Ahmun   M  Unknown  ...
7087      Swimming      Coast Guard personnel   M  Unknown  ...
7088           NaN            Jules Patterson   M  Unknown  ...
7089      Swimming                       male   M       15  ...

                                 Species   \
0     Undetermined Bull shark most likely
1            Blue fish bite most probable
2                       Great White Shark
3                                 Unknown
4                           Bronze Whaler
...                                   ...
7085                                  NaN
7086                                  NaN
7087                                  NaN
7088                                  NaN
7089                                  NaN

                                                 Source  \
0            Simon de Marchi: 9 News: 7 News: ABC News:
1                          Keithe Cowley: Delmarva Now:
2             ABC News: 9 News: 7 News: Simon De Marchi
3                         The U.S. Sun: Simon De Marchi
4     ABC News: The Guardian:  Andrew Currie and Bob...
...                                                 ...
7085                   H. Taunton; N. Bartlett,  p. 234
7086              H. Taunton; N. Bartlett,  pp. 233-234
7087               F. Schwartz, p.23; C. Creswell, GSAF
7088                                The Sun, 10/20/1938
7089                                         S.W. Baker

                                 pdf  \
0                                NaN
1                                NaN
2                                NaN
3                                NaN
4                                NaN
...                              ...
7085          ND-0005-RoebuckBay.pdf
7086               ND-0004-Ahmun.pdf
7087  ND-0003-Ocracoke_1900-1905.pdf
7088      ND-0002-JulesPatterson.pdf
7089              ND-0001-Ceylon.pdf

                                           href formula  \
0                                                   NaN
1                                                   NaN
2                                                   NaN
3                                                   NaN
4                                                   NaN
...                                                 ...
7085  http://sharkattackfile.net/spreadsheets/pdf_di...
7086  http://sharkattackfile.net/spreadsheets/pdf_di...
7087  http://sharkattackfile.net/spreadsheets/pdf_di...
7088  http://sharkattackfile.net/spreadsheets/pdf_di...
7089  http://sharkattackfile.net/spreadsheets/pdf_di...

                                                   href Case Number  \
0                                                   NaN         NaN
1                                                   NaN         NaN
2                                                   NaN         NaN
3                                                   NaN         NaN
4                                                   NaN         NaN
...                                                 ...         ...
7085  http://sharkattackfile.net/spreadsheets/pdf_di...     ND.0005
7086  http://sharkattackfile.net/spreadsheets/pdf_di...     ND.0004
7087  http://sharkattackfile.net/spreadsheets/pdf_di...     ND.0003
7088  http://sharkattackfile.net/spreadsheets/pdf_di...     ND.0002
7089  http://sharkattackfile.net/spreadsheets/pdf_di...     ND.0001

     Case Number.1 original order Unnamed: 21 Unnamed: 22
0              NaN            NaN         NaN         NaN
1              NaN            NaN         NaN         NaN
2              NaN            NaN         NaN         NaN
3              NaN            NaN         NaN         NaN
4              NaN            NaN         NaN         NaN
...            ...            ...         ...         ...
7085       ND.0005            6.0         NaN         NaN
7086       ND.0004            5.0         NaN         NaN
7087       ND.0003            4.0         NaN         NaN
7088       ND.0002            3.0         NaN         NaN
7089       ND.0001            2.0         NaN         NaN

[7090 rows x 23 columns]

In [4]:
df["Age"].unique()

array(['39', 'Unknown', '38', '16', '22', '30+', "50's", '55', '13', '11',
       '27', '12', '26', '56', '24', '25', '61', '40', '14', '50+', '54',
       '48', '57', '8', '63', '9', '19', '7', '85', '69', '18', '66',
       '21', '37', '20', '42', '45', '30', '40+', '29', '35', '58', '17',
       '36', '23', '28', '60+', '68', '33', '15', '41', '43',
       'Middle age', '49', '46', '65', '64', '32', '10', '62', '52', '44',
       '47', '59', '50', '34', '30s', '20/30', '20s', '77', '60', '!2',
       '73', '50s', '67', '6', '53', '51', '31', '40s', 'teen', 'Teen',
       'M', '!6', '!!', '71', '75', '45 and 15', '70', '4', '28 & 22',
       '22, 57, 31', '60s', "20's", '74', '9 & 60', 'a minor', '3', '82',
       '40?', '72', '18 months', '28 & 26', '5', '86', '18 or 20',
       '12 or 13', '46 & 34', '28, 23 & 30', 'Teens', '36 & 26',
       '8 or 10', '84', '\xa0 ', ' ', '30 or 36', '6½', '21 & ?',
       '33 or 37', 'mid-30s', '23 & 20', ' 30', '7      &    31', ' 28',
       '20?', "60's", '32 & 30', '16 to 18', '87', 'Elderly', 'mid-20s',
       'Ca. 33', '74 ', '45 ', '21 or 26', '20 ', '>50', '18 to 22',
       'adult', '9 & 12', '? & 19', '9 months', '25 to 35', '23 & 26',
       '1', '(adult)', '33 & 37', '25 or 28', '37, 67, 35, 27,  ? & 27',
       '21, 34,24 & 35', '30 & 32', '50 & 30', '17 & 35', 'X',
       '"middle-age"', '13 or 18', '34 & 19', '33 & 26', '2 to 3 months',
       'MAKE LINE GREEN', ' 43', '81', '"young"', '7 or 8', '78',
       '17 & 16', 'F', 'Both 11', '9 or 10', 'young', '36 & 23', '  ',
       'A.M.', '?    &   14', '10 or 12', '31 or 33', '2½', '13 or 14'],
      dtype=object)

In [5]:
df["Age"] = df["Age"].replace("?", "NA").fillna("NA")

In [6]:
df["Age"] = df["Age"].replace({
    "Teen" : "NA",
    "teen" : "NA",
    "a minor" : "NA",
    "Middle age" : "NA",
    "Unknown" : "NA",
    "Elderly" : "NA",
    "M" : "NA"
})

In [7]:
df["Age"] = df["Age"].str.replace("+", "", regex=False)
df["Age"] = df["Age"].str.replace("?", "", regex=False)
df["Age"] = df["Age"].str.replace("s", "", regex=False)
df["Age"] = df["Age"].str.replace("!", "", regex=False)

In [8]:
df["Age"] = pd.to_numeric(df["Age"], errors="coerce")

In [9]:
print(df)

             Date    Year          Type             Country  \
0        24th May  2026.0    Unprovoked           Australia
1        17th May  2026.0  Questionable                 USA
2        16th May  2026.0    Unprovoked           Australia
3      14th April  2026.0    UNprovoked            Maldives
4       3rd April  2026.0    Unprovoked           Australia
...           ...     ...           ...                 ...
7085  Before 1903     0.0    Unprovoked           AUSTRALIA
7086  Before 1903     0.0    Unprovoked           AUSTRALIA
7087    1900-1905     0.0    Unprovoked                 USA
7088    1883-1889     0.0    Unprovoked              PANAMA
7089    1845-1853     0.0    Unprovoked  CEYLON (SRI LANKA)

                  State                                     Location  \
0            Queensland                                Kennedy Shoal
1              Maryland                        Assateague State Park
2     Western Australia              Horseshoe Reef  Rottnest Island
3      Gaafu Alif Atoll                                      Kooddoo
4       South Australia  Middleton Beach Fleurieu Peninsula Adelaide
...                 ...                                          ...
7085  Western Australia                                  Roebuck Bay
7086  Western Australia                                          NaN
7087     North Carolina                               Ocracoke Inlet
7088                NaN                         Panama Bay 8ºN, 79ºW
7089   Eastern Province          Below the English fort, Trincomalee

          Activity                       Name Sex   Age  ...  \
0     Spearfishing              Michael Jensz   M  39.0  ...
1          Surfing              Brendan Oster   M   NaN  ...
2       Skindiving           Steven Mattaboni   M  38.0  ...
3         Swimming  Not stated - on honeymoon   M   NaN  ...
4          Surfing       Oliver Tokic-Bensley   M  16.0  ...
...            ...                        ...  ..   ...  ...
7085        Diving                       male   M   NaN  ...
7086  Pearl diving                      Ahmun   M   NaN  ...
7087      Swimming      Coast Guard personnel   M   NaN  ...
7088           NaN            Jules Patterson   M   NaN  ...
7089      Swimming                       male   M  15.0  ...

                                 Species   \
0     Undetermined Bull shark most likely
1            Blue fish bite most probable
2                       Great White Shark
3                                 Unknown
4                           Bronze Whaler
...                                   ...
7085                                  NaN
7086                                  NaN
7087                                  NaN
7088                                  NaN
7089                                  NaN

                                                 Source  \
0            Simon de Marchi: 9 News: 7 News: ABC News:
1                          Keithe Cowley: Delmarva Now:
2             ABC News: 9 News: 7 News: Simon De Marchi
3                         The U.S. Sun: Simon De Marchi
4     ABC News: The Guardian:  Andrew Currie and Bob...
...                                                 ...
7085                   H. Taunton; N. Bartlett,  p. 234
7086              H. Taunton; N. Bartlett,  pp. 233-234
7087               F. Schwartz, p.23; C. Creswell, GSAF
7088                                The Sun, 10/20/1938
7089                                         S.W. Baker

                                 pdf  \
0                                NaN
1                                NaN
2                                NaN
3                                NaN
4                                NaN
...                              ...
7085          ND-0005-RoebuckBay.pdf
7086               ND-0004-Ahmun.pdf
7087  ND-0003-Ocracoke_1900-1905.pdf
7088      ND-0002-JulesPatterson.pdf
7089              ND-0001-Ceylon.pdf

                                           href formula  \
0                                                   NaN
1                                                   NaN
2                                                   NaN
3                                                   NaN
4                                                   NaN
...                                                 ...
7085  http://sharkattackfile.net/spreadsheets/pdf_di...
7086  http://sharkattackfile.net/spreadsheets/pdf_di...
7087  http://sharkattackfile.net/spreadsheets/pdf_di...
7088  http://sharkattackfile.net/spreadsheets/pdf_di...
7089  http://sharkattackfile.net/spreadsheets/pdf_di...

                                                   href Case Number  \
0                                                   NaN         NaN
1                                                   NaN         NaN
2                                                   NaN         NaN
3                                                   NaN         NaN
4                                                   NaN         NaN
...                                                 ...         ...
7085  http://sharkattackfile.net/spreadsheets/pdf_di...     ND.0005
7086  http://sharkattackfile.net/spreadsheets/pdf_di...     ND.0004
7087  http://sharkattackfile.net/spreadsheets/pdf_di...     ND.0003
7088  http://sharkattackfile.net/spreadsheets/pdf_di...     ND.0002
7089  http://sharkattackfile.net/spreadsheets/pdf_di...     ND.0001

     Case Number.1 original order Unnamed: 21 Unnamed: 22
0              NaN            NaN         NaN         NaN
1              NaN            NaN         NaN         NaN
2              NaN            NaN         NaN         NaN
3              NaN            NaN         NaN         NaN
4              NaN            NaN         NaN         NaN
...            ...            ...         ...         ...
7085       ND.0005            6.0         NaN         NaN
7086       ND.0004            5.0         NaN         NaN
7087       ND.0003            4.0         NaN         NaN
7088       ND.0002            3.0         NaN         NaN
7089       ND.0001            2.0         NaN         NaN

[7090 rows x 23 columns]

Clean the Fatal Column

In [10]:
#clean Fatal column
df["Fatal Y/N"] = df["Fatal Y/N"].where(df["Fatal Y/N"].isin(["Y", "N"]), "Unknown")
print(df)

             Date    Year          Type             Country  \
0        24th May  2026.0    Unprovoked           Australia
1        17th May  2026.0  Questionable                 USA
2        16th May  2026.0    Unprovoked           Australia
3      14th April  2026.0    UNprovoked            Maldives
4       3rd April  2026.0    Unprovoked           Australia
...           ...     ...           ...                 ...
7085  Before 1903     0.0    Unprovoked           AUSTRALIA
7086  Before 1903     0.0    Unprovoked           AUSTRALIA
7087    1900-1905     0.0    Unprovoked                 USA
7088    1883-1889     0.0    Unprovoked              PANAMA
7089    1845-1853     0.0    Unprovoked  CEYLON (SRI LANKA)

                  State                                     Location  \
0            Queensland                                Kennedy Shoal
1              Maryland                        Assateague State Park
2     Western Australia              Horseshoe Reef  Rottnest Island
3      Gaafu Alif Atoll                                      Kooddoo
4       South Australia  Middleton Beach Fleurieu Peninsula Adelaide
...                 ...                                          ...
7085  Western Australia                                  Roebuck Bay
7086  Western Australia                                          NaN
7087     North Carolina                               Ocracoke Inlet
7088                NaN                         Panama Bay 8ºN, 79ºW
7089   Eastern Province          Below the English fort, Trincomalee

          Activity                       Name Sex   Age  ...  \
0     Spearfishing              Michael Jensz   M  39.0  ...
1          Surfing              Brendan Oster   M   NaN  ...
2       Skindiving           Steven Mattaboni   M  38.0  ...
3         Swimming  Not stated - on honeymoon   M   NaN  ...
4          Surfing       Oliver Tokic-Bensley   M  16.0  ...
...            ...                        ...  ..   ...  ...
7085        Diving                       male   M   NaN  ...
7086  Pearl diving                      Ahmun   M   NaN  ...
7087      Swimming      Coast Guard personnel   M   NaN  ...
7088           NaN            Jules Patterson   M   NaN  ...
7089      Swimming                       male   M  15.0  ...

                                 Species   \
0     Undetermined Bull shark most likely
1            Blue fish bite most probable
2                       Great White Shark
3                                 Unknown
4                           Bronze Whaler
...                                   ...
7085                                  NaN
7086                                  NaN
7087                                  NaN
7088                                  NaN
7089                                  NaN

                                                 Source  \
0            Simon de Marchi: 9 News: 7 News: ABC News:
1                          Keithe Cowley: Delmarva Now:
2             ABC News: 9 News: 7 News: Simon De Marchi
3                         The U.S. Sun: Simon De Marchi
4     ABC News: The Guardian:  Andrew Currie and Bob...
...                                                 ...
7085                   H. Taunton; N. Bartlett,  p. 234
7086              H. Taunton; N. Bartlett,  pp. 233-234
7087               F. Schwartz, p.23; C. Creswell, GSAF
7088                                The Sun, 10/20/1938
7089                                         S.W. Baker

                                 pdf  \
0                                NaN
1                                NaN
2                                NaN
3                                NaN
4                                NaN
...                              ...
7085          ND-0005-RoebuckBay.pdf
7086               ND-0004-Ahmun.pdf
7087  ND-0003-Ocracoke_1900-1905.pdf
7088      ND-0002-JulesPatterson.pdf
7089              ND-0001-Ceylon.pdf

                                           href formula  \
0                                                   NaN
1                                                   NaN
2                                                   NaN
3                                                   NaN
4                                                   NaN
...                                                 ...
7085  http://sharkattackfile.net/spreadsheets/pdf_di...
7086  http://sharkattackfile.net/spreadsheets/pdf_di...
7087  http://sharkattackfile.net/spreadsheets/pdf_di...
7088  http://sharkattackfile.net/spreadsheets/pdf_di...
7089  http://sharkattackfile.net/spreadsheets/pdf_di...

                                                   href Case Number  \
0                                                   NaN         NaN
1                                                   NaN         NaN
2                                                   NaN         NaN
3                                                   NaN         NaN
4                                                   NaN         NaN
...                                                 ...         ...
7085  http://sharkattackfile.net/spreadsheets/pdf_di...     ND.0005
7086  http://sharkattackfile.net/spreadsheets/pdf_di...     ND.0004
7087  http://sharkattackfile.net/spreadsheets/pdf_di...     ND.0003
7088  http://sharkattackfile.net/spreadsheets/pdf_di...     ND.0002
7089  http://sharkattackfile.net/spreadsheets/pdf_di...     ND.0001

     Case Number.1 original order Unnamed: 21 Unnamed: 22
0              NaN            NaN         NaN         NaN
1              NaN            NaN         NaN         NaN
2              NaN            NaN         NaN         NaN
3              NaN            NaN         NaN         NaN
4              NaN            NaN         NaN         NaN
...            ...            ...         ...         ...
7085       ND.0005            6.0         NaN         NaN
7086       ND.0004            5.0         NaN         NaN
7087       ND.0003            4.0         NaN         NaN
7088       ND.0002            3.0         NaN         NaN
7089       ND.0001            2.0         NaN         NaN

[7090 rows x 23 columns]

Clean the Sex Column

In [11]:
def clean_sex(value):

    if pd.isna(value):
        return "Unknown"

    value = str(value).strip().upper()

    if value.startswith("M"):
        return "Male"

    elif value.startswith("F"):
        return "Female"

    else:
        return "Unknown"

In [12]:
df["sex_clean"] = df["Sex"].apply(clean_sex)
df["sex_clean"].value_counts()

sex_clean
Male       5693
Female      813
Unknown     584
Name: count, dtype: int64

Cleaning Activity Column

In [13]:
df["Activity"].nunique()

1612

In [14]:
def clean_activity(activity):

    if pd.isna(activity):
        return "Unknown"

    activity = str(activity).lower().strip()
    if activity in ["not stated", "unknown", "n/a", "na", "", "not known"]:
        return "Unknown"

    if re.search(r"swim|bathing|floating|treading water|wading", activity):
        return "Swimming"

    elif re.search(r"surf|board|foiling", activity):
        return "Surfing"

    elif re.search(r"div|skindiving|scuba", activity):
        return "Diving"

    elif re.search(r"spearfish", activity):
        return "Spearfishing"

    elif re.search(r"fish|angling", activity):
        return "Fishing"
    elif re.search(r"snorkel", activity):
        return "Snorkeling"

    else:
        return "Other"

In [15]:
df["activity_clean"] = df["Activity"].apply(clean_activity)
df["activity_clean"].value_counts()

activity_clean
Swimming        1782
Surfing         1750
Other            966
Fishing          795
Diving           638
Unknown          590
Spearfishing     429
Snorkeling       140
Name: count, dtype: int64

In [16]:
# this code is replacing all the missing data in the "activity" and "sex" column with the text "unknown"
df["Activity"] = df["Activity"].fillna("Unknown")
df["Sex"] = df["Sex"].fillna("Unknown")

Cleaning of the Year column

In [17]:
df["Year"].head(20)

0     2026.0
1     2026.0
2     2026.0
3     2026.0
4     2026.0
5     2026.0
6     2026.0
7     2026.0
8     2026.0
9     2026.0
10    2026.0
11    2026.0
12    2026.0
13    2026.0
14    2026.0
15    2026.0
16    2026.0
17    2026.0
18    2026.0
19    2026.0
Name: Year, dtype: float64

In [18]:
#give a look to the type of the data
df["Year"].dtype

dtype('float64')

In [19]:
#check how many null values we have at year
df["Year"].isna().sum()

np.int64(2)

In [20]:
#since there are only 2 of them, I will check them individually
df[df["Year"].isna()]

,Date,Year,Type,Country,State,Location,Activity,Name,Sex,Age,...,pdf,href formula,href,Case Number,Case Number.1,original order,Unnamed: 21,Unnamed: 22,sex_clean,activity_clean
943,Reported 08-Jan-2017,NaN,Invalid,AUSTRALIA,Queensland,NaN,Spearfishing,Kerry Daniel,M,35.0,...,2017.01.08.R-KerryDaniel.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2017.01.08.R,2017.01.08.R,6142.0,NaN,NaN,Male,Spearfishing
6858,Reported 19-Aug-1836,NaN,Unprovoked,ENGLAND,Cumberland,Whitehaven,Swimming,a boy,M,NaN,...,1835.08.19.R-Whitehaven.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1836.08.19.R,1836.08.19.R,230.0,NaN,NaN,Male,Swimming

In [21]:
# the column Date actually included details about the year of the attack, so I can add them manually being only 2
df.loc[943, "Year"] = 2017
df.loc[6858, "Year"] = 1836

In [22]:
#double checking there are not null values any longer
df["Year"].isna().sum()

np.int64(0)

In [23]:
# making sure there are no negative values in the Year column
(df["Year"] < 0).sum()

np.int64(0)

In [24]:
# looking for outliers in mins and max to make sure they make sense
df["Year"].describe()

count    7090.000000
mean     1936.205783
std       270.366563
min         0.000000
25%      1948.000000
50%      1987.000000
75%      2010.000000
max      2026.000000
Name: Year, dtype: float64

In [25]:
# list of the smallest values (all 0s)
df["Year"].nsmallest(40)

6961    0.0
6962    0.0
6963    0.0
6964    0.0
6965    0.0
6966    0.0
6967    0.0
6968    0.0
6969    0.0
6970    0.0
6971    0.0
6972    0.0
6973    0.0
6974    0.0
6975    0.0
6976    0.0
6977    0.0
6978    0.0
6979    0.0
6980    0.0
6981    0.0
6982    0.0
6983    0.0
6984    0.0
6985    0.0
6986    0.0
6987    0.0
6988    0.0
6989    0.0
6990    0.0
6991    0.0
6992    0.0
6993    0.0
6994    0.0
6995    0.0
6996    0.0
6997    0.0
6998    0.0
6999    0.0
7000    0.0
Name: Year, dtype: float64

In [26]:
# they represent 1.8% of our total dataset
(df["Year"] == 0).sum()
#129 / 7090 ≈ 1.8%

np.int64(129)

In [27]:
#df.loc[df["Year"] == 0, "Year"] = pd.NA

In [28]:
# let's give a look to the very old years 
df[df["Year"] < 1800]["Year"].value_counts().sort_index()

Year
0.0       129
5.0         1
77.0        1
1000.0      1
1500.0      1
1518.0      1
1543.0      1
1554.0      1
1555.0      1
1580.0      1
1595.0      1
1617.0      1
1637.0      1
1638.0      1
1640.0      1
1642.0      2
1691.0      1
1700.0      3
1703.0      1
1721.0      1
1723.0      1
1733.0      1
1738.0      1
1742.0      1
1748.0      1
1749.0      1
1751.0      1
1753.0      1
1755.0      1
1758.0      1
1764.0      1
1767.0      1
1771.0      1
1776.0      2
1779.0      1
1780.0      1
1783.0      1
1784.0      1
1785.0      1
1786.0      1
1787.0      1
1788.0      1
1791.0      1
1792.0      1
1797.0      1
Name: count, dtype: int64

In [29]:
# let's see individually these especially old years:
df[df["Year"].isin([5, 77, 1000, 0])]

,Date,Year,Type,Country,State,Location,Activity,Name,Sex,Age,...,pdf,href formula,href,Case Number,Case Number.1,original order,Unnamed: 21,Unnamed: 22,sex_clean,activity_clean
6958,Ca.789-1033 A.D,1000.0,Unprovoked,USA,Puerto Rico,Archeological site,Unknown,male,M,29.0,...,1000AD-PuertoRico.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1000.00.00,1000.00.00,133.0,NaN,NaN,Male,Unknown
6959,Ca. 77 A.D.,77.0,Unprovoked,NaN,Ionian Sea,NaN,Sponge diving,males,M,NaN,...,77AD-Pliny.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,0077.00.00,0077.00.00,132.0,NaN,NaN,Male,Diving
6960,Ca. 5 A.D.,5.0,Unprovoked,AUSTRALIA,New South Wales,Bondi,Unknown,male,M,NaN,...,5BC-AustralianAboriginal.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,5BC-Australia,5BC,131.0,NaN,NaN,Male,Unknown
6961,Ca. 214 B.C.,0.0,Unprovoked,NaN,Ionian Sea,NaN,Ascending from a dive,"Tharsys, a sponge diver",M,NaN,...,214BC-Tharsys.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,214BC-Tharsus,214BC,130.0,NaN,NaN,Male,Diving
6962,Ca. 336.B.C..,0.0,Unprovoked,GREECE,Piraeus,In the haven of Cantharus,Washing his pig in preparation for a religious...,A candidate for initiation,M,NaN,...,336-BC-Carnathus.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,336BC-Csrnathus,336BC,129.0,NaN,NaN,Male,Other
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7085,Before 1903,0.0,Unprovoked,AUSTRALIA,Western Australia,Roebuck Bay,Diving,male,M,NaN,...,ND-0005-RoebuckBay.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0005,ND.0005,6.0,NaN,NaN,Male,Diving
7086,Before 1903,0.0,Unprovoked,AUSTRALIA,Western Australia,NaN,Pearl diving,Ahmun,M,NaN,...,ND-0004-Ahmun.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0004,ND.0004,5.0,NaN,NaN,Male,Diving
7087,1900-1905,0.0,Unprovoked,USA,North Carolina,Ocracoke Inlet,Swimming,Coast Guard personnel,M,NaN,...,ND-0003-Ocracoke_1900-1905.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0003,ND.0003,4.0,NaN,NaN,Male,Swimming
7088,1883-1889,0.0,Unprovoked,PANAMA,NaN,"Panama Bay 8ºN, 79ºW",Unknown,Jules Patterson,M,NaN,...,ND-0002-JulesPatterson.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0002,ND.0002,3.0,NaN,NaN,Male,Unknown
7089,1845-1853,0.0,Unprovoked,CEYLON (SRI LANKA),Eastern Province,"Below the English fort, Trincomalee",Swimming,male,M,15.0,...,ND-0001-Ceylon.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0001,ND.0001,2.0,NaN,NaN,Male,Swimming

In [30]:
# let's see what's happening with year 0. Does date give us some information we could use? 
df[df["Year"] == 0]["Date"].sample(20)

6997           No date, late 1960s
7085                   Before 1903
7019    No date, Before 8-May-1965
7044                   Before 1956
7060                  World War II
7002                         1950s
7055                   1940 - 1950
7029                         1960s
7068                       No date
7087                     1900-1905
7040                   Before 1958
7021          No date, Before 1902
6961                  Ca. 214 B.C.
7088                     1883-1889
6980                   Before 2012
7058                   Before 1905
7010                   Before 1996
7007               Before Feb-1998
7065                   Before 1927
6965                 Ca. 1010  BC
Name: Date, dtype: object

In [31]:
# checking smallest values
df["Year"].value_counts().sort_index().head(20)

Year
0.0       129
5.0         1
77.0        1
1000.0      1
1500.0      1
1518.0      1
1543.0      1
1554.0      1
1555.0      1
1580.0      1
1595.0      1
1617.0      1
1637.0      1
1638.0      1
1640.0      1
1642.0      2
1691.0      1
1700.0      3
1703.0      1
1721.0      1
Name: count, dtype: int64

In [32]:
#turning the data into int
df["Year"] = df["Year"].astype("Int64")

In [33]:
#making usre it worked
df["Year"].dtype

Int64Dtype()

In [34]:
#checking unique values once more
df["Year"].unique()

<IntegerArray>
[2026, 2025, 2024, 2023, 2022, 2021, 2020, 2019, 2018, 2017,
 ...
 1580, 1555, 1554, 1543, 1518, 1500, 1000,   77,    5,    0]
Length: 261, dtype: Int64

In [35]:
# seeing the most common years
df["Year"].value_counts(dropna=False).head(30)

Year
2015    143
2017    142
2016    133
0       129
2011    128
2014    126
2018    124
2013    122
2008    122
2009    120
2012    117
2019    114
2007    113
2021    111
2023    109
2005    103
2006    103
2010    101
2020    101
2022     98
2000     97
1960     93
1959     93
2004     92
2001     92
2003     92
2002     88
1962     86
1961     78
1995     76
Name: count, dtype: Int64

In [36]:
# all years in the 2000s
df.loc[df["Year"] > 1999, "Year"].value_counts().sort_index()

Year
2000     97
2001     92
2002     88
2003     92
2004     92
2005    103
2006    103
2007    113
2008    122
2009    120
2010    101
2011    128
2012    117
2013    122
2014    126
2015    143
2016    133
2017    142
2018    124
2019    114
2020    101
2021    111
2022     98
2023    109
2024     52
2025     68
2026     27
Name: count, dtype: Int64

In [37]:
# summing them
(df["Year"] > 1990).sum()

np.int64(3371)

In [38]:
#cheking the last 50 years
(df["Year"] > 1975).sum()

np.int64(3964)

In [39]:
# numbers by century

century_counts = (
    df[df["Year"] > 0] 
    .assign(Century=lambda x: (x["Year"] // 100) * 100)
    ["Century"]
    .value_counts()
    .sort_index()
)

century_counts

Century
0          2
1000       1
1500       7
1600       7
1700      31
1800     574
1900    3501
2000    2838
Name: count, dtype: Int64

In [40]:
# by decade
decade_counts = (
    df[df["Year"] > 0]
    .assign(Decade=lambda x: (x["Year"] // 10) * 10)
    ["Decade"]
    .value_counts()
    .sort_index()
)

decade_counts

Decade
0          1
70         1
1000       1
1500       1
1510       1
1540       1
1550       2
1580       1
1590       1
1610       1
1630       2
1640       3
1690       1
1700       4
1720       2
1730       2
1740       3
1750       4
1760       2
1770       4
1780       7
1790       3
1800      12
1810      11
1820      17
1830      22
1840      43
1850      42
1860      68
1870      91
1880     118
1890     150
1900     154
1910     148
1920     207
1930     275
1940     283
1950     467
1960     618
1970     339
1980     438
1990     572
2000    1022
2010    1250
2020     566
Name: count, dtype: Int64

In [41]:
#decades from 1800 
decade_counts = (
    df[df["Year"] >= 1800]
    .assign(Decade=lambda x: (x["Year"] // 10) * 10)
    ["Decade"]
    .value_counts()
    .sort_index()
)

decade_counts

Decade
1800      12
1810      11
1820      17
1830      22
1840      43
1850      42
1860      68
1870      91
1880     118
1890     150
1900     154
1910     148
1920     207
1930     275
1940     283
1950     467
1960     618
1970     339
1980     438
1990     572
2000    1022
2010    1250
2020     566
Name: count, dtype: Int64

Cleaning Country Column

In [42]:
# fast look to the content in Country
df["Country"].describe()

count     7040
unique     253
top        USA
freq      2581
Name: Country, dtype: object

In [43]:
# checking the most common countries
df["Country"].value_counts(dropna=False)

Country
USA                        2581
AUSTRALIA                  1482
SOUTH AFRICA                597
NEW ZEALAND                 144
PAPUA NEW GUINEA            136
                           ...
Sierra Leone                  1
BRITISH VIRGIN ISLANDS        1
NEVIS                         1
PALESTINIAN TERRITORIES       1
CEYLON (SRI LANKA)            1
Name: count, Length: 254, dtype: int64

In [44]:
#checking unique values in order
sorted(df["Country"].dropna().unique())

[' PHILIPPINES',
 ' TONGA',
 'ADMIRALTY ISLANDS',
 'AFRICA',
 'ALGERIA',
 'AMERICAN SAMOA',
 'ANDAMAN / NICOBAR ISLANDAS',
 'ANDAMAN ISLANDS',
 'ANGOLA',
 'ANTIGUA',
 'ARGENTINA',
 'ARUBA',
 'ASIA?',
 'ATLANTIC OCEAN',
 'AUSTRALIA',
 'AZORES',
 'Australia',
 'BAHAMAS',
 'BAHREIN',
 'BANGLADESH',
 'BARBADOS',
 'BAY OF BENGAL',
 'BELIZE',
 'BERMUDA',
 'BRAZIL',
 'BRITISH ISLES',
 'BRITISH NEW GUINEA',
 'BRITISH VIRGIN ISLANDS',
 'BRITISH WEST INDIES',
 'BURMA',
 'Bahamas',
 'Belize',
 'Between PORTUGAL & INDIA',
 'Brazil',
 'British Overseas Territory',
 'CANADA',
 'CAPE VERDE',
 'CARIBBEAN SEA',
 'CAYMAN ISLANDS',
 'CENTRAL PACIFIC',
 'CEYLON',
 'CEYLON (SRI LANKA)',
 'CHILE',
 'CHINA',
 'COLOMBIA',
 'COLUMBIA',
 'COMOROS',
 'COOK ISLANDS',
 'COSTA RICA',
 'CRETE',
 'CROATIA',
 'CUBA',
 'CURACAO',
 'CYPRUS',
 'Canary Islands',
 'Cayman Islands',
 'Coast of AFRICA',
 'Columbia',
 'Coral Sea',
 'Costa Rica',
 'DIEGO GARCIA',
 'DJIBOUTI',
 'DOMINICAN REPUBLIC',
 'ECUADOR',
 'EGYPT',
 'EGYPT ',
 'EGYPT / ISRAEL',
 'EL SALVADOR',
 'ENGLAND',
 'EQUATORIAL GUINEA / CAMEROON',
 'Egypt',
 'FALKLAND ISLANDS',
 'FEDERATED STATES OF MICRONESIA',
 'FIJI',
 'FRANCE',
 'FRENCH POLYNESIA',
 'Fiji',
 'French Polynesia',
 'GABON',
 'GEORGIA',
 'GHANA',
 'GRAND CAYMAN',
 'GREECE',
 'GREENLAND',
 'GRENADA',
 'GUAM',
 'GUATEMALA',
 'GUINEA',
 'GULF OF ADEN',
 'GUYANA',
 'HAITI',
 'HONDURAS',
 'HONG KONG',
 'Hawaii',
 'Honduras',
 'ICELAND',
 'INDIA',
 'INDIAN OCEAN',
 'INDIAN OCEAN?',
 'INDONESIA',
 'IRAN',
 'IRAN / IRAQ',
 'IRAQ',
 'IRELAND',
 'ISRAEL',
 'ITALY',
 'ITALY / CROATIA',
 'Indonesia',
 'Israel',
 'JAMAICA',
 'JAPAN',
 'JAVA',
 'JOHNSTON ISLAND',
 'JORDAN',
 'Jamaica',
 'KENYA',
 'KIRIBATI',
 'KOREA',
 'KUWAIT',
 'LEBANON',
 'LIBERIA',
 'LIBYA',
 'MADAGASCAR',
 'MALAYSIA',
 'MALDIVE ISLANDS',
 'MALDIVES',
 'MALTA',
 'MARSHALL ISLANDS',
 'MARTINIQUE',
 'MAURITIUS',
 'MAYOTTE',
 'MEDITERRANEAN SEA',
 'MEXICO',
 'MEXICO ',
 'MICRONESIA',
 'MID ATLANTIC OCEAN',
 'MID-PACIFC OCEAN',
 'MONACO',
 'MONTENEGRO',
 'MOZAMBIQUE',
 'Maldive Islands',
 'Maldives',
 'MeXICO',
 'Mexico',
 'Morocco',
 'Mozambique',
 'NAMIBIA',
 'NETHERLANDS ANTILLES',
 'NEVIS',
 'NEW BRITAIN',
 'NEW CALEDONIA',
 'NEW GUINEA',
 'NEW ZEALAND',
 'NICARAGUA',
 'NICARAGUA ',
 'NIGERIA',
 'NORTH ATLANTIC OCEAN',
 'NORTH ATLANTIC OCEAN ',
 'NORTH PACIFIC OCEAN',
 'NORTH SEA',
 'NORTHERN ARABIAN SEA',
 'NORTHERN MARIANA ISLANDS',
 'NORWAY',
 'New Caledonia',
 'New Zealand',
 'OCEAN',
 'OKINAWA',
 'PACIFIC OCEAN',
 'PACIFIC OCEAN ',
 'PALAU',
 'PALESTINIAN TERRITORIES',
 'PANAMA',
 'PAPUA NEW GUINEA',
 'PARAGUAY',
 'PERSIAN GULF',
 'PERU',
 'PHILIPPINES',
 'PORTUGAL',
 'PUERTO RICO',
 'Philippines',
 'Puerto Rico',
 'RED SEA',
 'RED SEA / INDIAN OCEAN',
 'RED SEA?',
 'REUNION',
 'REUNION ISLAND',
 'ROATAN',
 'RUSSIA',
 'SAMOA',
 'SAN DOMINGO',
 'SAUDI ARABIA',
 'SCOTLAND',
 'SENEGAL',
 'SEYCHELLES',
 'SIERRA LEONE',
 'SINGAPORE',
 'SLOVENIA',
 'SOLOMON ISLANDS',
 'SOLOMON ISLANDS / VANUATU',
 'SOMALIA',
 'SOUTH AFRICA',
 'SOUTH ATLANTIC OCEAN',
 'SOUTH CHINA SEA',
 'SOUTH KOREA',
 'SOUTH PACIFIC OCEAN',
 'SOUTHWEST PACIFIC OCEAN',
 'SPAIN',
 'SRI LANKA',
 'ST HELENA, British overseas territory',
 'ST KITTS / NEVIS',
 'ST MARTIN',
 'ST. MAARTIN',
 'ST. MARTIN',
 'SUDAN',
 'SUDAN?',
 'SWEDEN',
 'SYRIA',
 'Samoa',
 'Seychelles',
 'Sierra Leone',
 'South Africa',
 'Spain',
 'TAIWAN',
 'TANZANIA',
 'TASMAN SEA',
 'THAILAND',
 'THE BALKANS',
 'TOBAGO',
 'TONGA',
 'TRINIDAD',
 'TRINIDAD & TOBAGO',
 'TUNISIA',
 'TURKEY',
 'TURKS & CAICOS',
 'TURKS and CaICOS',
 'TUVALU',
 'Thailand',
 'Tobago',
 'Turks and Caicos',
 'UNITED ARAB EMIRATES',
 'UNITED ARAB EMIRATES (UAE)',
 'UNITED KINGDOM',
 'URUGUAY',
 'US Virgin Islands',
 'USA',
 'VANUATU',
 'VENEZUELA',
 'VIETNAM',
 'Vanuatu',
 'WEST INDIES',
 'WESTERN SAMOA',
 'YEMEN',
 'YEMEN ']

In [45]:
# checking number of null values
df["Country"].isna().sum()

np.int64(50)

In [46]:
# it is 0.7% of our dataset 
df["Country"].isna().mean() * 100

np.float64(0.7052186177715092)

In [47]:
# counting unique values
df["Country"].nunique()

253

In [48]:
# checking unique values from top to lower
df["Country"].value_counts(dropna=False).head(30)

Country
USA                 2581
AUSTRALIA           1482
SOUTH AFRICA         597
NEW ZEALAND          144
PAPUA NEW GUINEA     136
BAHAMAS              136
BRAZIL               122
MEXICO               103
ITALY                 72
FIJI                  67
NEW CALEDONIA         65
PHILIPPINES           63
REUNION               60
NaN                   50
Australia             49
CUBA                  49
EGYPT                 49
MOZAMBIQUE            46
SPAIN                 46
INDIA                 41
FRENCH POLYNESIA      37
JAPAN                 36
CROATIA               35
PANAMA                32
JAMAICA               30
SOLOMON ISLANDS       30
IRAN                  29
ENGLAND               25
INDONESIA             24
HONG KONG             24
Name: count, dtype: int64

In [49]:
# removing blanks before and after each word
df["Country"] = df["Country"].str.upper()

In [50]:
# checking the values once more now that the columns have been stripped 
df["Country"].value_counts(dropna=False).head(30)

Country
USA                 2581
AUSTRALIA           1531
SOUTH AFRICA         599
NEW ZEALAND          146
BAHAMAS              142
PAPUA NEW GUINEA     136
BRAZIL               123
MEXICO               106
ITALY                 72
FIJI                  70
NEW CALEDONIA         68
PHILIPPINES           64
REUNION               60
MOZAMBIQUE            52
EGYPT                 51
NaN                   50
CUBA                  49
SPAIN                 47
INDIA                 41
FRENCH POLYNESIA      40
JAPAN                 36
CROATIA               35
PANAMA                32
JAMAICA               32
SOLOMON ISLANDS       30
IRAN                  29
ENGLAND               25
INDONESIA             25
GREECE                24
HONG KONG             24
Name: count, dtype: int64

In [51]:
# double checking the number of how many countries are left
df["Country"].nunique()

221

In [52]:
df["Country"] = df["Country"].str.strip()

In [53]:
# checking countries with ?
df[df["Country"].str.contains(r"\?", na=False)]

,Date,Year,Type,Country,State,Location,Activity,Name,Sex,Age,...,pdf,href formula,href,Case Number,Case Number.1,original order,Unnamed: 21,Unnamed: 22,sex_clean,activity_clean
5119,Apr-1954,1954,Provoked,SUDAN?,Red Sea,Southern part,Spearfishing,Jean Foucher-Createau,M,NaN,...,1954.04.00-Foucher-Creteau.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1954.04.00,1954.04.00,1967.0,NaN,NaN,Male,Spearfishing
6673,Reported 30-Nov-1872,1872,Unprovoked,INDIAN OCEAN?,NaN,NaN,Swimming to avoid capture,Malay pirates,M,NaN,...,1872.11.30.R-MalayPirates.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1872.11.30.R,1872.11.30.R,415.0,NaN,NaN,Male,Swimming
7016,"No date, Before 1969",0,Unprovoked,RED SEA?,NaN,NaN,Free diving,Jill Reed,F,NaN,...,ND-0085-JillReed.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0085,ND.0085,75.0,NaN,NaN,Female,Diving
7079,Before 1911,0,Unprovoked,ASIA?,NaN,NaN,Swimming,Mr. Masury,M,NaN,...,ND-0011-Masury.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0011,ND.0011,12.0,NaN,NaN,Male,Swimming

In [54]:
# checking those that are not countries
non_countries = [
    "INDIAN OCEAN",
    "RED SEA",
    "ATLANTIC OCEAN",
    "CORAL SEA",
    "BAY OF BENGAL",
    "SOUTH CHINA SEA",
    "GULF OF ADEN",
    "NORTHERN ARABIAN SEA"
]

df[df["Country"].isin(non_countries)]["Country"].value_counts()

Country
ATLANTIC OCEAN          17
INDIAN OCEAN             7
CORAL SEA                1
GULF OF ADEN             1
NORTHERN ARABIAN SEA     1
SOUTH CHINA SEA          1
RED SEA                  1
BAY OF BENGAL            1
Name: count, dtype: int64

In [55]:
# unique countries (not very useful )
countries = sorted(df["Country"].dropna().unique())
countries

['ADMIRALTY ISLANDS',
 'AFRICA',
 'ALGERIA',
 'AMERICAN SAMOA',
 'ANDAMAN / NICOBAR ISLANDAS',
 'ANDAMAN ISLANDS',
 'ANGOLA',
 'ANTIGUA',
 'ARGENTINA',
 'ARUBA',
 'ASIA?',
 'ATLANTIC OCEAN',
 'AUSTRALIA',
 'AZORES',
 'BAHAMAS',
 'BAHREIN',
 'BANGLADESH',
 'BARBADOS',
 'BAY OF BENGAL',
 'BELIZE',
 'BERMUDA',
 'BETWEEN PORTUGAL & INDIA',
 'BRAZIL',
 'BRITISH ISLES',
 'BRITISH NEW GUINEA',
 'BRITISH OVERSEAS TERRITORY',
 'BRITISH VIRGIN ISLANDS',
 'BRITISH WEST INDIES',
 'BURMA',
 'CANADA',
 'CANARY ISLANDS',
 'CAPE VERDE',
 'CARIBBEAN SEA',
 'CAYMAN ISLANDS',
 'CENTRAL PACIFIC',
 'CEYLON',
 'CEYLON (SRI LANKA)',
 'CHILE',
 'CHINA',
 'COAST OF AFRICA',
 'COLOMBIA',
 'COLUMBIA',
 'COMOROS',
 'COOK ISLANDS',
 'CORAL SEA',
 'COSTA RICA',
 'CRETE',
 'CROATIA',
 'CUBA',
 'CURACAO',
 'CYPRUS',
 'DIEGO GARCIA',
 'DJIBOUTI',
 'DOMINICAN REPUBLIC',
 'ECUADOR',
 'EGYPT',
 'EGYPT / ISRAEL',
 'EL SALVADOR',
 'ENGLAND',
 'EQUATORIAL GUINEA / CAMEROON',
 'FALKLAND ISLANDS',
 'FEDERATED STATES OF MICRONESIA',
 'FIJI',
 'FRANCE',
 'FRENCH POLYNESIA',
 'GABON',
 'GEORGIA',
 'GHANA',
 'GRAND CAYMAN',
 'GREECE',
 'GREENLAND',
 'GRENADA',
 'GUAM',
 'GUATEMALA',
 'GUINEA',
 'GULF OF ADEN',
 'GUYANA',
 'HAITI',
 'HAWAII',
 'HONDURAS',
 'HONG KONG',
 'ICELAND',
 'INDIA',
 'INDIAN OCEAN',
 'INDIAN OCEAN?',
 'INDONESIA',
 'IRAN',
 'IRAN / IRAQ',
 'IRAQ',
 'IRELAND',
 'ISRAEL',
 'ITALY',
 'ITALY / CROATIA',
 'JAMAICA',
 'JAPAN',
 'JAVA',
 'JOHNSTON ISLAND',
 'JORDAN',
 'KENYA',
 'KIRIBATI',
 'KOREA',
 'KUWAIT',
 'LEBANON',
 'LIBERIA',
 'LIBYA',
 'MADAGASCAR',
 'MALAYSIA',
 'MALDIVE ISLANDS',
 'MALDIVES',
 'MALTA',
 'MARSHALL ISLANDS',
 'MARTINIQUE',
 'MAURITIUS',
 'MAYOTTE',
 'MEDITERRANEAN SEA',
 'MEXICO',
 'MICRONESIA',
 'MID ATLANTIC OCEAN',
 'MID-PACIFC OCEAN',
 'MONACO',
 'MONTENEGRO',
 'MOROCCO',
 'MOZAMBIQUE',
 'NAMIBIA',
 'NETHERLANDS ANTILLES',
 'NEVIS',
 'NEW BRITAIN',
 'NEW CALEDONIA',
 'NEW GUINEA',
 'NEW ZEALAND',
 'NICARAGUA',
 'NIGERIA',
 'NORTH ATLANTIC OCEAN',
 'NORTH PACIFIC OCEAN',
 'NORTH SEA',
 'NORTHERN ARABIAN SEA',
 'NORTHERN MARIANA ISLANDS',
 'NORWAY',
 'OCEAN',
 'OKINAWA',
 'PACIFIC OCEAN',
 'PALAU',
 'PALESTINIAN TERRITORIES',
 'PANAMA',
 'PAPUA NEW GUINEA',
 'PARAGUAY',
 'PERSIAN GULF',
 'PERU',
 'PHILIPPINES',
 'PORTUGAL',
 'PUERTO RICO',
 'RED SEA',
 'RED SEA / INDIAN OCEAN',
 'RED SEA?',
 'REUNION',
 'REUNION ISLAND',
 'ROATAN',
 'RUSSIA',
 'SAMOA',
 'SAN DOMINGO',
 'SAUDI ARABIA',
 'SCOTLAND',
 'SENEGAL',
 'SEYCHELLES',
 'SIERRA LEONE',
 'SINGAPORE',
 'SLOVENIA',
 'SOLOMON ISLANDS',
 'SOLOMON ISLANDS / VANUATU',
 'SOMALIA',
 'SOUTH AFRICA',
 'SOUTH ATLANTIC OCEAN',
 'SOUTH CHINA SEA',
 'SOUTH KOREA',
 'SOUTH PACIFIC OCEAN',
 'SOUTHWEST PACIFIC OCEAN',
 'SPAIN',
 'SRI LANKA',
 'ST HELENA, BRITISH OVERSEAS TERRITORY',
 'ST KITTS / NEVIS',
 'ST MARTIN',
 'ST. MAARTIN',
 'ST. MARTIN',
 'SUDAN',
 'SUDAN?',
 'SWEDEN',
 'SYRIA',
 'TAIWAN',
 'TANZANIA',
 'TASMAN SEA',
 'THAILAND',
 'THE BALKANS',
 'TOBAGO',
 'TONGA',
 'TRINIDAD',
 'TRINIDAD & TOBAGO',
 'TUNISIA',
 'TURKEY',
 'TURKS & CAICOS',
 'TURKS AND CAICOS',
 'TUVALU',
 'UNITED ARAB EMIRATES',
 'UNITED ARAB EMIRATES (UAE)',
 'UNITED KINGDOM',
 'URUGUAY',
 'US VIRGIN ISLANDS',
 'USA',
 'VANUATU',
 'VENEZUELA',
 'VIETNAM',
 'WEST INDIES',
 'WESTERN SAMOA',
 'YEMEN']

In [56]:
#turning it into a df to check it better
countries_df = pd.DataFrame({
    "Country": sorted(df["Country"].dropna().unique())
})

countries_df

                        Country
0             ADMIRALTY ISLANDS
1                        AFRICA
2                       ALGERIA
3                AMERICAN SAMOA
4    ANDAMAN / NICOBAR ISLANDAS
..                          ...
208                   VENEZUELA
209                     VIETNAM
210                 WEST INDIES
211               WESTERN SAMOA
212                       YEMEN

[213 rows x 1 columns]

In [57]:
# counting values in the new df
country_counts = df["Country"].value_counts(dropna=False)

countries_df["count"] = countries_df["Country"].map(country_counts)

countries_df

                        Country  count
0             ADMIRALTY ISLANDS      1
1                        AFRICA      1
2                       ALGERIA      1
3                AMERICAN SAMOA      3
4    ANDAMAN / NICOBAR ISLANDAS      1
..                          ...    ...
208                   VENEZUELA     11
209                     VIETNAM     15
210                 WEST INDIES      2
211               WESTERN SAMOA      1
212                       YEMEN      9

[213 rows x 2 columns]

In [58]:
# renaming countries
country_mapping = {
    "COLUMBIA": "COLOMBIA",
    "CEYLON": "SRI LANKA",
    "CEYLON (SRI LANKA)": "SRI LANKA",
    "MALDIVE ISLANDS": "MALDIVES",
    "REUNION ISLAND": "REUNION",
    "ST. MARTIN": "ST MARTIN",
    "ST. MAARTIN": "ST MARTIN",
    "TURKS AND CAICOS": "TURKS & CAICOS",
    "UNITED ARAB EMIRATES (UAE)": "UNITED ARAB EMIRATES"
}

In [59]:
# applying replace
df["Country"] = df["Country"].replace(country_mapping)

In [60]:
# checking number of countries again
df["Country"].nunique()

204

In [61]:
# checking how many cases we have now for these countries
df["Country"].value_counts().loc[
    ["COLOMBIA", "SRI LANKA", "MALDIVES", "REUNION"]
]

Country
COLOMBIA     13
SRI LANKA    18
MALDIVES     10
REUNION      65
Name: count, dtype: int64

In [62]:
# checking how many cases for these countries to understand if it makes sense to rename them 
df["Country"].value_counts().loc[
    [
        "ENGLAND",
        "SCOTLAND",
        "UNITED KINGDOM",
        "TRINIDAD",
        "TOBAGO",
        "TRINIDAD & TOBAGO",
        "MICRONESIA",
        "FEDERATED STATES OF MICRONESIA",
        "NEW GUINEA",
        "PAPUA NEW GUINEA",
        "BRITISH NEW GUINEA"
    ]
]

Country
ENGLAND                            25
SCOTLAND                            8
UNITED KINGDOM                     11
TRINIDAD                            1
TOBAGO                              3
TRINIDAD & TOBAGO                   3
MICRONESIA                          3
FEDERATED STATES OF MICRONESIA      1
NEW GUINEA                         10
PAPUA NEW GUINEA                  136
BRITISH NEW GUINEA                  1
Name: count, dtype: int64

In [63]:
# checking countries that have the word ocean sea gulf in their names
df.loc[
    df["Country"].str.contains("OCEAN|SEA|GULF", case=False, na=False),
    "Country"
].value_counts()

Country
PACIFIC OCEAN                            19
ATLANTIC OCEAN                           17
SOUTH ATLANTIC OCEAN                     12
CARIBBEAN SEA                             8
NORTH PACIFIC OCEAN                       7
INDIAN OCEAN                              7
MID ATLANTIC OCEAN                        5
NORTH ATLANTIC OCEAN                      5
PERSIAN GULF                              4
SOUTH PACIFIC OCEAN                       2
SOUTHWEST PACIFIC OCEAN                   2
MEDITERRANEAN SEA                         2
ST HELENA, BRITISH OVERSEAS TERRITORY     2
OCEAN                                     1
TASMAN SEA                                1
MID-PACIFC OCEAN                          1
INDIAN OCEAN?                             1
CORAL SEA                                 1
NORTH SEA                                 1
RED SEA / INDIAN OCEAN                    1
BRITISH OVERSEAS TERRITORY                1
RED SEA                                   1
SOUTH CHINA SEA                           1
NORTHERN ARABIAN SEA                      1
GULF OF ADEN                              1
RED SEA?                                  1
Name: count, dtype: int64

In [64]:
# checking those with ? or word Islandas and quantities
countries_df[
    countries_df["Country"].str.contains(
        r"\?|ISLANDAS",
        case=False,
        na=False
    )
]

                        Country  count
4    ANDAMAN / NICOBAR ISLANDAS      1
10                        ASIA?      1
84                INDIAN OCEAN?      1
153                    RED SEA?      1
184                      SUDAN?      1

In [65]:
df[df["Country"].str.contains("ANDAMAN", na=False)]["Country"].value_counts()

Country
ANDAMAN / NICOBAR ISLANDAS    1
ANDAMAN ISLANDS               1
Name: count, dtype: int64

In [66]:
#renaming
country_mapping = {
    "ANDAMAN / NICOBAR ISLANDAS": "ANDAMAN / NICOBAR ISLANDS",
    "SUDAN?": "SUDAN",
    "INDIAN OCEAN?": "INDIAN OCEAN",
    "RED SEA?": "RED SEA"
}

In [67]:
df["Country"] = df["Country"].replace(country_mapping)

In [68]:
# how many countries we end up with 
df["Country"].nunique()

201

In [69]:
# filling null values as Unknown
df["Country"] = df["Country"].fillna("Unknown")

In [70]:
df["Country"].isna().sum()

np.int64(0)

In [71]:
#checking that null values increased of 1 only (Unknown)
df["Country"].nunique()

202

CLEANING TYPE COLUMN

In [72]:
# checking unique values
df["Type"].unique()

array(['Unprovoked', 'Questionable', 'UNprovoked', 'Provoked',
       'unprovoked', ' Provoked', 'Watercraft', 'Sea Disaster', nan, '?',
       'Unconfirmed', 'Unverified', 'Invalid', 'Under investigation',
       'Boat'], dtype=object)

In [73]:
#stripping and lowering all the cases
df["Type"] = df["Type"].str.strip().str.lower()

In [74]:
# since there are no many unique values I map them to replace later on

type_mapping = {
    "unprovoked": "Unprovoked",
    "provoked": "Provoked",
    "watercraft": "Watercraft",
    "boat": "Watercraft",
    "sea disaster": "Sea Disaster",
    "questionable": "Questionable",
    "unconfirmed": "Questionable",
    "unverified": "Questionable",
    "under investigation": "Questionable",
    "invalid": "Invalid",
    "?": "Unknown"
}

In [75]:
# applying the mapping into the df
df["Type"] = df["Type"].replace(type_mapping).fillna("Unknown")

In [76]:
#checking to see the new unique values
df["Type"].unique()

array(['Unprovoked', 'Questionable', 'Provoked', 'Watercraft',
       'Sea Disaster', 'Unknown', 'Invalid'], dtype=object)

In [77]:
# we clean the columns we selected
cols = ["Country", "State", "Location"]

for col in cols :  
    df[col] = df[col].astype(str).str.strip() # suppress the unecessary spaces in the text
    df[col] = df[col].str.replace(r"[.,]+$", " ",regex=True) #suppress the comas or points at the end of the text
    df[col] = df[col].replace(["nan", "NAN", "none", " "],np.nan) # Convert the nan

In [78]:
df[["Country", "State", "Location"]].head(20) # we verify the cleaning for the 20 first rows

,Country,State,Location
0,AUSTRALIA,Queensland,Kennedy Shoal
1,USA,Maryland,Assateague State Park
2,AUSTRALIA,Western Australia,Horseshoe Reef Rottnest Island
3,MALDIVES,Gaafu Alif Atoll,Kooddoo
4,AUSTRALIA,South Australia,Middleton Beach Fleurieu Peninsula Adelaide
5,BAHAMAS,Andros Island,Fresh Creek
6,AUSTRALIA,South Australia,Cape Jaffa Limestone Coast
7,AUSTRALIA,NSW,Little Avalon Beach
8,USA,California,Big River Beach Mendocino County
9,AUSTRALIA,Western Australia,Exmouth
10,AUSTRALIA,Western Australia,Exmouth
11,AUSTRALIA,Queensland,Lady Elliott Island
12,NEW CALEDONIA,Noumea,Anse Vata near Point Magnin
13,CAYMAN ISLANDS,Little Cayman Island,Caribbean Sea
14,BRAZIL,Recife,Del Chifre Beach in Olinda
15,AUSTRALIA,NSW,Angels Beach East Ballina
16,AUSTRALIA,Tasmania,Cooee Beach west of Burnie
17,AUSTRALIA,NSW,Point Plomber North of Port Macquarie
18,AUSTRALIA,NSW,Dee Why
19,AUSTRALIA,NSW,North Steyne

In [79]:
# For the Country column we will upper the text
df["Country"] = df["Country"].str.upper()

In [80]:
# we amend the variation
country_mapping = {
    "USA" : "UNITED STATES",
    "U.S.A" : "UNITED STATES",
    "UNITED STATES OF AMERICA" : "UNITED STATES",
    "AUSTRALIA" : "AUSTRALIA",
    "ENGLAND" : "UNITED KINGDOM",
    "SCOTLAND" : "UNITED KINGDOM",
    "WALES" : "UNITED KINGDOM",
}
df["Country"] = df["Country"].replace(country_mapping)

In [81]:
df["Country"].value_counts().head(20)

Country
UNITED STATES       2581
AUSTRALIA           1531
SOUTH AFRICA         599
NEW ZEALAND          146
BAHAMAS              142
PAPUA NEW GUINEA     136
BRAZIL               123
MEXICO               107
ITALY                 72
FIJI                  70
NEW CALEDONIA         68
REUNION               65
PHILIPPINES           65
EGYPT                 53
MOZAMBIQUE            52
UNKNOWN               50
CUBA                  49
SPAIN                 47
UNITED KINGDOM        44
INDIA                 41
Name: count, dtype: int64

Cleaning of the state column

In [82]:
# for the State column cleansing we start with harmonazing the format
df["State"] = df["State"].str.title()

In [83]:
# We correct now any possible abbreviations.
state_mapping = {
    "Nsw" : "New South Wales",
    "Qld" : "Queensland",
    "Wa" : "Western Australia",
    "Sa" : "South Australia"
}
df["State"] = df["State"].replace(state_mapping)

In [84]:
df["State"].value_counts().head(20)

State
Florida                  1193
New South Wales           539
Queensland                356
Hawaii                    345
California                328
Western Australia         247
Kwazulu-Natal             219
Western Cape Province     197
South Carolina            176
Eastern Cape Province     168
North Carolina            122
South Australia           122
Victoria                   98
Texas                      83
Pernambuco                 80
North Island               76
Torres Strait              72
New Jersey                 57
New York                   48
South Island               45
Name: count, dtype: int64

Cleaning of the Location Column

In [85]:
print(df["Location"].head(20))

0                                   Kennedy Shoal
1                           Assateague State Park
2                 Horseshoe Reef  Rottnest Island
3                                         Kooddoo
4     Middleton Beach Fleurieu Peninsula Adelaide
5                                     Fresh Creek
6                      Cape Jaffa Limestone Coast
7                             Little Avalon Beach
8                Big River Beach Mendocino County
9                                         Exmouth
10                                        Exmouth
11                            Lady Elliott Island
12                    Anse Vata near Point Magnin
13                                  Caribbean Sea
14                     Del Chifre Beach in Olinda
15                      Angels Beach East Ballina
16                     Cooee Beach west of Burnie
17          Point Plomber North of Port Macquarie
18                                        Dee Why
19                                   North Steyne
Name: Location, dtype: object

In [86]:
print(df["Location"].nunique()) # check the total of unique values

4588

In [87]:
print(df["Location"].isna().sum()) #check the sum of na

567

In [88]:
df["Location"] = (
    df["Location"]
    .astype(str) # define the type as string.
    .str.strip() #suppress the non needed spaces.
    .str.replace(r"\s+", " ", regex=True)
    .str.replace(r"[.,]+$", " ", regex=True) #suppress punctuation at the end of the text
    .str.title()
)

In [89]:
# We restore the actual missing values.
df["Location"] = df["Location"].replace(
    ["Nan", "None", " ", "Unkown"],
    np.nan
)

In [90]:
# As the dataset conatains distances in miles or kms we will suppress them to keep only the location name.
# So that we have: before==> 10 miles north of Durban, after ==> North of Durban.
df["Location"] = df["Location"].str.replace(
    r"\b\d+(\.\d+)?\s*(mile|miles|km|kilometer|kilometers|yard|yards|meter|meters|m)\b",
    " ",
    regex=True,
    case=False
)

In [91]:
# We strip out the remaining numbers.
df["Location"] = df["Location"].str.replace(
    r"\b\d+\b",
    " ",
    regex=True
)

In [92]:
# We clean the remained spaces that have been created by the cleansing before.
df["Location"] = (
    df["Location"]
    .str.replace(r"\s+", " ", regex=True)
    .str.strip()
)

In [93]:
generic_locations = [
    "Offshore",
    "Off Shore",
    "Off Coast",
    "At Sea",
    "Open Sea",
    "Ocean",
    "Near Shore",
    "Unknown"
]

df["Location"] = df["Location"].replace(
    generic_locations,
    np.nan
)

In [94]:
# finally we check & control.

In [95]:
# check the missing values.
df["Location"].isna().sum()

np.int64(573)

In [96]:
# check unique localisation values.
df["Location"].nunique()

4549

In [97]:
# list the top 20 of the localisations.
df["Location"].value_counts().head(20)

Location
New Smyrna Beach, Volusia County                 198
Daytona Beach, Volusia County                     35
Cocoa Beach, Brevard County                       33
Ponce Inlet, Volusia County                       28
Myrtle Beach, Horry County                        22
Melbourne Beach, Brevard County                   21
Isle Of Palms, Charleston County                  18
Durban                                            18
Boa Viagem, Recife                                14
Piedade                                           14
Jensen Beach, Martin County                       13
Jacksonville Beach, Duval County                  13
Ponce Inlet, New Smyrna Beach, Volusia County     13
Juno Beach, Palm Beach County                     12
Palm Beach, Palm Beach County                     11
Mossel Bay                                        11
Ormond Beach, Volusia County                      11
Ahvaz, On The Karun River                         11
New Smyrna Beach                                  10
Boa Viagem Beach, Recife                          10
Name: count, dtype: int64

Cleaning of the Time Column

In [98]:
# 4. Time Column cleansing
# This column is very challenging, the dataset is very dirty but as we were coached by the best of the best we decided to give it a try.
# we need to ==> 1.clean the format, 2.Extract an hour when it exists, 3. Create a business‑oriented category(Morning, Afternoon, Evening, Night)

In [99]:
# First we look at the unique values.
df['Time'].sample(20)

67        1100hrs
6175          NaN
3455        13h30
5874          NaN
5391          NaN
357         10h30
1811          NaN
6144    Afternoon
1970        19h20
3872        13h15
1972        12h00
4831     Midnight
6959          NaN
3524          NaN
5887          NaN
1684          NaN
755           NaN
3056        14h00
3188        13h26
5792          NaN
Name: Time, dtype: object

In [100]:
df['Time'].isna().sum()

np.int64(3527)

In [101]:
df['Time'].value_counts().head(20)

Time
Afternoon    215
11h00        140
Morning      135
15h00        127
16h00        123
12h00        122
14h00        115
16h30         88
13h00         85
17h30         83
17h00         81
14h30         76
18h00         75
11h30         74
10h00         73
15h30         73
13h30         70
Night         64
10h30         61
09h00         61
Name: count, dtype: int64

In [102]:
# Now we manage the real missing values.
df["Time"] = df["Time"].replace(
    ["None", "", " "],
    np.nan
)

In [103]:

df["Time"] = (
    df["Time"]
    .astype(str) # convert all the values into string/text to uniformize the dataset.
    .str.strip() # suppress the unecessary spaces at the begining and the end.
    .str.replace(r"\s+", " ", regex=True) # suppress the double spaces by just one.
)

In [104]:
df["Time"].dtype

dtype('O')

In [105]:
# We check the suppression of the spaces.
df["Time"].sample(20)

3365    17h30
3150    13h20
735     12h00
4526      nan
1254    11h00
4575      nan
4826      nan
3634      nan
5926    Night
4585    night
2868    17h40
6398      nan
4198    16h00
6935      nan
7057      nan
6231      nan
3786    10h15
2934    13h00
4745    20h00
2537      nan
Name: Time, dtype: object

In [106]:
# Now we can standardize the time formats
# 1.We replace the format 17h30 => 17:30
# 2.We replace "h" by ":" , 17h30 => 17:30
# 3.We replace all the dots. ex: 13.30 ==> 13:30


df["Time"] = df["Time"].str.replace(r"(\d{1,2})h(\d{0,2})", 
                                    lambda m: f"{m.group(1)}:{m.group(2) if m.group(2) else '00'}",
                                    regex=True)

df["Time"] = df["Time"].str.replace(r"^(\d{2})(\d{2})\b",
                                    r"\1:\2",
                                    regex=True)

df["Time"] = df["Time"].str.replace(r"(\d{1,2})\.(\d{2})",
                                    r"\1:\2",
                                    regex=True)

In [107]:
# We control that the format are now harmonized : 

df["Time"].value_counts().head(30)

Time
nan               3529
Afternoon          215
11:00              140
Morning            136
15:00              128
16:00              126
12:00              122
14:00              117
16:30               88
13:00               87
17:30               83
17:00               81
14:30               76
18:00               75
11:30               75
10:00               74
15:30               73
13:30               70
Night               64
10:30               61
09:00               61
08:00               43
12:30               42
Evening             39
09:30               39
18:30               36
Late afternoon      35
07:30               35
08:30               34
?                   30
Name: count, dtype: int64

In [108]:
# Now we control if some dirty formats remain:

df["Time"].str.contains(r"h", na=False).sum()

np.int64(91)

In [109]:
# We check if the HHMM is reduced.

df["Time"].str.contains(r"\d{4}", na=False).sum()

np.int64(3)

In [110]:
# Finally we check that format HH.MM have been removed.

df["Time"].str.contains(r"\.", na=False).sum()

np.int64(29)

In [111]:
# we need to harmonize the business values periods by using a custom/mapping dictionary.
# This will also allow to complete the missing hours data.

time_mapping = {
    "Morning" : "Morning",
    "Early Morning" : "Morning",
    "Noon" : "Afternoon",
    "Midday" : "Afternoon",
    "Afternoon" : "Afternoon",
    "Late afternoon" : "Afternoon",
    "Evening" : "Evening",
    "Night" : "Night",
    "Late Night" : "Night",
    "Dawn" : "Morning",
    "Before Dawn" : "Morning",
    "Sunset" : "Evening",
    "Unknown" : np.nan
}

df["Time"] = df["Time"].replace(time_mapping)

In [112]:
# Now we extract the hour as we want to create a business variable (morning, afternoon...)No need to keep the minutes or seconds.

df["Hour"] = pd.to_numeric(
    df["Time"].str.extract(r"(\d{1,2})")[0],
    errors="coerce"
)

In [113]:
# Check the extracted hour.
# We try to see how many values have not been extracted
df["Hour"].describe()
df["Hour"].isna().sum()

np.int64(4211)

In [114]:
# Then we to create a business variable that will be usefull for the dashboard.

def time_period(hour):
    if pd.isna(hour):
        return np.nan
    elif 5 <= hour < 12:
        return "Morning"
    elif 12 <= hour < 17:
        return "Afternoon"
    elif 17 <= hour < 21:
        return "Evening"
    else:
        return "Night"

In [115]:
# Application of the variable created.
df["Time_Period"] = df["Hour"].apply(time_period)

In [116]:
print(df.columns) # We print all the columns to check the ones we have created.

Index(['Date', 'Year', 'Type', 'Country', 'State', 'Location', 'Activity',
       'Name', 'Sex', 'Age', 'Injury', 'Fatal Y/N', 'Time', 'Species ',
       'Source', 'pdf', 'href formula', 'href', 'Case Number', 'Case Number.1',
       'original order', 'Unnamed: 21', 'Unnamed: 22', 'sex_clean',
       'activity_clean', 'Hour', 'Time_Period'],
      dtype='object')

In [117]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7090 entries, 0 to 7089
Data columns (total 27 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Date            7090 non-null   object
 1   Year            7090 non-null   Int64
 2   Type            7090 non-null   object
 3   Country         7090 non-null   object
 4   State           6603 non-null   object
 5   Location        6517 non-null   object
 6   Activity        7090 non-null   object
 7   Name            6872 non-null   object
 8   Sex             7090 non-null   object
 9   Age             3976 non-null   float64
 10  Injury          7054 non-null   object
 11  Fatal Y/N       7090 non-null   object
 12  Time            7088 non-null   object
 13  Species         3959 non-null   object
 14  Source          7070 non-null   object
 15  pdf             6799 non-null   object
 16  href formula    6794 non-null   object
 17  href            6796 non-null   object
 18  Case Number     6798 non-null   object
 19  Case Number.1   6797 non-null   object
 20  original order  6799 non-null   float64
 21  Unnamed: 21     1 non-null      object
 22  Unnamed: 22     2 non-null      object
 23  sex_clean       7090 non-null   object
 24  activity_clean  7090 non-null   object
 25  Hour            2879 non-null   float64
 26  Time_Period     2879 non-null   object
dtypes: Int64(1), float64(3), object(23)
memory usage: 1.5+ MB

In [118]:
df.head(20)

,Date,Year,Type,Country,State,Location,Activity,Name,Sex,Age,...,href,Case Number,Case Number.1,original order,Unnamed: 21,Unnamed: 22,sex_clean,activity_clean,Hour,Time_Period
0,24th May,2026,Unprovoked,AUSTRALIA,Queensland,Kennedy Shoal,Spearfishing,Michael Jensz,M,39.0,...,NaN,NaN,NaN,NaN,NaN,NaN,Male,Spearfishing,11.0,Morning
1,17th May,2026,Questionable,UNITED STATES,Maryland,Assateague State Park,Surfing,Brendan Oster,M,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Male,Surfing,NaN,NaN
2,16th May,2026,Unprovoked,AUSTRALIA,Western Australia,Horseshoe Reef Rottnest Island,Skindiving,Steven Mattaboni,M,38.0,...,NaN,NaN,NaN,NaN,NaN,NaN,Male,Diving,10.0,Morning
3,14th April,2026,Unprovoked,MALDIVES,Gaafu Alif Atoll,Kooddoo,Swimming,Not stated - on honeymoon,M,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Male,Swimming,NaN,NaN
4,3rd April,2026,Unprovoked,AUSTRALIA,South Australia,Middleton Beach Fleurieu Peninsula Adelaide,Surfing,Oliver Tokic-Bensley,M,16.0,...,NaN,NaN,NaN,NaN,NaN,NaN,Male,Surfing,NaN,NaN
5,26th March,2026,Unprovoked,BAHAMAS,Andros Island,Fresh Creek,Swimming,Australian woman,F,22.0,...,NaN,NaN,NaN,NaN,NaN,NaN,Female,Swimming,17.0,Evening
6,25th March,2026,Unprovoked,AUSTRALIA,South Australia,Cape Jaffa Limestone Coast,Diving,Luke Kuhn,M,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Male,Diving,NaN,NaN
7,22nd-23rd March,2026,Unprovoked,AUSTRALIA,New South Wales,Little Avalon Beach,Surfing,Unknown,M,30.0,...,NaN,NaN,NaN,NaN,NaN,NaN,Male,Surfing,NaN,NaN
8,18th March,2026,Unprovoked,UNITED STATES,California,Big River Beach Mendocino County,Surfing,Unknown,M,39.0,...,NaN,NaN,NaN,NaN,NaN,NaN,Male,Surfing,17.0,Evening
9,14th March,2026,Unprovoked,AUSTRALIA,Western Australia,Exmouth,Swimming,Unknown,F,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Female,Swimming,10.0,Morning
10,10th March,2026,Unprovoked,AUSTRALIA,Western Australia,Exmouth,Wing Foiling,Dave Daniell,M,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Male,Surfing,8.0,Morning
11,5th March,2026,Unprovoked,AUSTRALIA,Queensland,Lady Elliott Island,Snorkeling,Unknown,M,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Male,Snorkeling,8.0,Morning
12,22nd February,2026,Unprovoked,NEW CALEDONIA,Noumea,Anse Vata Near Point Magnin,Wing Foiling,Cyril Chevalier,M,55.0,...,NaN,NaN,NaN,NaN,NaN,NaN,Male,Surfing,NaN,NaN
13,6th February,2026,Unprovoked,CAYMAN ISLANDS,Little Cayman Island,Caribbean Sea,Diving,Bekley White,M,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Male,Diving,NaN,NaN
14,29th January,2026,Unprovoked,BRAZIL,Recife,Del Chifre Beach In Olinda,Swimming,Deivson Rocha Dantas,M,13.0,...,NaN,NaN,NaN,NaN,NaN,NaN,Male,Swimming,NaN,NaN
15,29th January,2026,Unprovoked,AUSTRALIA,New South Wales,Angels Beach East Ballina,Surfing,Unnamed man,M,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Male,Surfing,11.0,Morning
16,24th January,2026,Unprovoked,AUSTRALIA,Tasmania,Cooee Beach West Of Burnie,Swimming,Megan Stokes,F,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Female,Swimming,18.0,Evening
17,20th January,2026,Unprovoked,AUSTRALIA,New South Wales,Point Plomber North Of Port Macquarie,Surfing,Paul Zvirdinas,M,39.0,...,NaN,NaN,NaN,NaN,NaN,NaN,Male,Surfing,8.0,Morning
18,19th January,2026,Unprovoked,AUSTRALIA,New South Wales,Dee Why,Surfing,Unknown,M,11.0,...,NaN,NaN,NaN,NaN,NaN,NaN,Male,Surfing,11.0,Morning
19,19th January,2026,Unprovoked,AUSTRALIA,New South Wales,North Steyne,Surfing,Andre de Ruyter,M,27.0,...,NaN,NaN,NaN,NaN,NaN,NaN,Male,Surfing,18.0,Evening

In [119]:
# Step 2: Strip whitespace from column names
df.columns = df.columns.str.strip()

# Step 3: Remove unnamed columns
df_dataset = df.loc[:, ~df.columns.str.contains("^Unnamed")]

# Step 4: Drop unwanted columns
df_clean = df_dataset.drop(columns=[
    'Name', 
    'Species', 
    'Source', 
    'pdf',  
    'Injury', 
    'href formula', 
    'href', 
    'Case Number', 
    'Case Number.1', 
    'original order'
])

# Step 5: Convert Year column to numeric
df_clean["Year"] = pd.to_numeric(df_clean["Year"], errors="coerce")

# Step 6: Define the year range
current_year = 2026
start_year   = current_year - 50   # = 1976

# Step 7: Filter df_clean for the last 50 years
df_last_50 = df_clean.loc[(df_clean["Year"] >= start_year) & 
                           (df_clean["Year"] <= current_year)]


# Step 8: Remove blank/null values from Fatal (Y/N) column
df_last_50_clean = df_last_50.dropna(subset=["Fatal Y/N"])

# Step 9: Remove empty string values from Fatal (Y/N) column
df_last_50_clean = df_last_50_clean[df_last_50_clean["Fatal Y/N"].str.strip() != ""]

# Step 10: Display results
print("Remaining columns:")
print(df_last_50_clean.columns.tolist())
print(f"\nYear Range                     : {start_year} to {current_year}")
print(f"Total Records                  : {len(df_clean)}")
print(f"Records (last 50 years)        : {len(df_last_50)}")
print(f"Records (blanks removed)       : {len(df_last_50_clean)}")


df_last_50_clean.head()

Remaining columns:
['Date', 'Year', 'Type', 'Country', 'State', 'Location', 'Activity', 'Sex', 'Age', 'Fatal Y/N', 'Time', 'sex_clean', 'activity_clean', 'Hour', 'Time_Period']

Year Range                     : 1976 to 2026
Total Records                  : 7090
Records (last 50 years)        : 3964
Records (blanks removed)       : 3964

,Date,Year,Type,Country,State,Location,Activity,Sex,Age,Fatal Y/N,Time,sex_clean,activity_clean,Hour,Time_Period
0,24th May,2026,Unprovoked,AUSTRALIA,Queensland,Kennedy Shoal,Spearfishing,M,39.0,Y,11:00:00rs,Male,Spearfishing,11.0,Morning
1,17th May,2026,Questionable,UNITED STATES,Maryland,Assateague State Park,Surfing,M,NaN,N,?,Male,Surfing,NaN,NaN
2,16th May,2026,Unprovoked,AUSTRALIA,Western Australia,Horseshoe Reef Rottnest Island,Skindiving,M,38.0,Y,10:00:00rs,Male,Diving,10.0,Morning
3,14th April,2026,Unprovoked,MALDIVES,Gaafu Alif Atoll,Kooddoo,Swimming,M,NaN,N,?,Male,Swimming,NaN,NaN
4,3rd April,2026,Unprovoked,AUSTRALIA,South Australia,Middleton Beach Fleurieu Peninsula Adelaide,Surfing,M,16.0,N,?,Male,Surfing,NaN,NaN

In [120]:
# Standardize Column Names
df_last_50_clean.columns = (
    df_last_50_clean.columns
      .str.strip()
      .str.lower()
      .str.replace(" ", "_")
)

In [121]:
df_last_50_clean.head(10)

,date,year,type,country,state,location,activity,sex,age,fatal_y/n,time,sex_clean,activity_clean,hour,time_period
0,24th May,2026,Unprovoked,AUSTRALIA,Queensland,Kennedy Shoal,Spearfishing,M,39.0,Y,11:00:00rs,Male,Spearfishing,11.0,Morning
1,17th May,2026,Questionable,UNITED STATES,Maryland,Assateague State Park,Surfing,M,NaN,N,?,Male,Surfing,NaN,NaN
2,16th May,2026,Unprovoked,AUSTRALIA,Western Australia,Horseshoe Reef Rottnest Island,Skindiving,M,38.0,Y,10:00:00rs,Male,Diving,10.0,Morning
3,14th April,2026,Unprovoked,MALDIVES,Gaafu Alif Atoll,Kooddoo,Swimming,M,NaN,N,?,Male,Swimming,NaN,NaN
4,3rd April,2026,Unprovoked,AUSTRALIA,South Australia,Middleton Beach Fleurieu Peninsula Adelaide,Surfing,M,16.0,N,?,Male,Surfing,NaN,NaN
5,26th March,2026,Unprovoked,BAHAMAS,Andros Island,Fresh Creek,Swimming,F,22.0,N,17:30:00rs,Female,Swimming,17.0,Evening
6,25th March,2026,Unprovoked,AUSTRALIA,South Australia,Cape Jaffa Limestone Coast,Diving,M,NaN,N,?,Male,Diving,NaN,NaN
7,22nd-23rd March,2026,Unprovoked,AUSTRALIA,New South Wales,Little Avalon Beach,Surfing,M,30.0,N,?,Male,Surfing,NaN,NaN
8,18th March,2026,Unprovoked,UNITED STATES,California,Big River Beach Mendocino County,Surfing,M,39.0,N,17:15:00rs,Male,Surfing,17.0,Evening
9,14th March,2026,Unprovoked,AUSTRALIA,Western Australia,Exmouth,Swimming,F,NaN,N,10:15:00rs,Female,Swimming,10.0,Morning

In [122]:
df_last_50_clean.to_csv("clean_shark_df.csv", index=False)